homeassistant:
  name: Home
  latitude: 45.493400
  longitude: 11.106900
  elevation: 430
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include_dir_merge_named customizations

config:

frontend:

http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  base_url: !secret base_url

updater:

discovery:

conversation:

history:

recorder:
  purge_days: 2

logbook:

sun:

#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  keepalive: 60
#  username: pi
#  password: !secret mqtt_password
#  protocol: 3.1

zwave:
  usb_path: /dev/zwave
  config_path: /home/hass/lib/lib/python3.5/site-packages/libopenzwave-0.3.1-py3.5-linux-x86_64.egg/config
  device_config: !include zwave_device_config.yaml

logger:
  default: warning
  #default: debug
  logs:
    homeassistant.components.device_tracker: debug
#    homeassistant.components.device_tracker.mqtt: debug
#    custom_components.telegram_webhooks: debug
#    custom_components.grafana_webhooks: debug
    homeassistant.components.http: debug
    homeassistant.components.shell_command: debug

device_tracker: !include device_trackers.yaml

notify: !include notify.yaml

media_player: !include media_players.yaml

sensor: !include_dir_merge_list sensors

zone: !include zones.yaml

automation: !include_dir_list automation

group: !include groups.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

shell_command: !include shell_command.yaml

script: !include_dir_named scripts


###########################################

weblink:
  entities:
    - name: Musica
      url: http://cubo.home:6680/musicbox_webclient
    - name: Grafana
      url: http://pi.csgalileo.org/grafana/
    - name: Cloud
      url: http://pi.csgalileo.org/cloud/

camera:
  - platform: foscam
    ip: 192.168.2.14
    port: 80
    username: foscam
    password: !secret foscam_c1
    # rtsp url: rtsp://foscam:foscam1@192.168.2.21:554/11
    # rtsp mcast: rtsp://192.168.2.21:554/11
  - platform: generic
    name: 'Bianca'
    still_image_url: http://192.168.2.12:80/cgi-bin/anv/images_cgi?channel=0&user=admin&pwd=admin
    # sito del costruttore: http://www.szsinocam.net/ (non il .com) 
    # model: szsinocam SN-IPC-5029CSW
    # rtsp url: rtsp://192.168.2.12:554/ucast/11


graphite:
  host: 127.0.0.1
  port: 2003

telegram_bot:
  platform: webhooks
  api_key: !secret telegram_token
  trusted_networks:
    - 149.154.167.197/32
    - 149.154.167.198/31
    - 149.154.167.200/29
    - 149.154.167.208/28
    - 149.154.167.224/29
    - 149.154.167.232/31
  allowed_chat_ids:
    - 73496590
    - 84015820
    #- -209766105


#microsoft_face:
#  api_key: !secret microsoft_api


grafana_webhooks:

panel_iframe:
  music:
    title: 'Music'
    url: !secret music_url

tts:
  - platform: google
    language: 'en'
  - platform: picotts
    language: 'en-US'
    #language: 'it_I'


