homeassistant:
  name: Home
  latitude: 45.493400
  longitude: 11.106900
  elevation: 430
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include_dir_merge_named customizations

frontend:

http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  base_url: !secret base_url

updater:

discovery:

conversation:

#history:

#recorder:
#  purge_days: 2

logbook:

sun:

#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  keepalive: 60
#  username: pi
#  password: !secret mqtt_password
#  protocol: 3.1

zwave:
  usb_path: /dev/ttyACM0
  config_path: /home/hass/lib/lib/python3.5/site-packages/libopenzwave-0.3.1-py3.5-linux-x86_64.egg/config

logger:
  default: warning
  logs:
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.device_tracker.mqtt: debug
    custom_components.telegram_webhooks: debug
    custom_components.grafana_webhooks: debug
    homeassistant.components.http: debug

device_tracker: !include device_trackers.yaml

notify: !include notify.yaml

media_player: !include media_players.yaml

sensor: !include_dir_merge_list sensors

zone: !include zones.yaml

automation: !include_dir_list automation

group: !include groups.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

shell_command: !include_dir_merge_named shell_command


###########################################

weblink:
  entities:
    - name: Musica
      url: http://cubo.home:6680/musicbox_webclient
    - name: Grafana
      url: http://pi.csgalileo.org/grafana/
    - name: Cloud
      url: http://pi.csgalileo.org/cloud/

camera:
  - platform: foscam
    ip: 192.168.2.14
    username: foscam
    password: !secret foscam_c1
  - platform: generic
    name: 'Bianca'
    still_image_url: http://192.168.2.12:80/cgi-bin/anv/images_cgi?channel=0&user=admin&pwd=admin


graphite:
  host: 127.0.0.1
  port: 2003

telegram_webhooks:
  api_key: !secret telegram_token
  #api_url: !secret telegram_webhook
  trusted_networks:
    - 149.154.167.197/32
    - 149.154.167.198/31
    - 149.154.167.200/29
    - 149.154.167.208/28
    - 149.154.167.224/29
    - 149.154.167.232/31
  user_id:
    scipio: 73496590


microsoft_face:
  api_key: !secret microsoft_api


grafana_webhooks:

panel_iframe:
  music:
    title: 'Music'
    url: !secret music_url
